type EmailListing = { residence: string; city: string; postal_code: string | null; housing_type: string; price_min_cents: number | null; price_max_cents: number | null; surface_m2: number | null; url: string; last_seen_at: string };

const template = `<!doctype html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>CROUS Alert</title><style>.cta-button:hover{background-color:#3d86f2!important}.cta-button{transition:background-color .1s ease}</style></head><body style="margin:0;padding:0;background:#f4f5f7;font-family:Arial,Helvetica,sans-serif;color:#111111"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f5f7;padding:24px 8px 34px"><tr><td align="center"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:600px;background:#ffffff;border:1px solid #e4e4e4;border-radius:18px;overflow:hidden;box-shadow:0 2px 8px rgba(17,17,17,.06)"><tr><td style="background:#e1120b;padding:28px 24px;border-radius:14px;color:#ffffff"><h1 style="font-size:26px;line-height:1.25;font-weight:500;text-align:center;margin:0;color:#ffffff">Nouveau logement disponible</h1></td></tr><tr><td style="padding:26px 24px 26px"><p style="font-size:18px;line-height:1.5;margin:0 0 22px;color:#111111"><strong>{{SUMMARY}}</strong></p>{{CARDS}}<p style="font-size:12px;line-height:1.6;color:#777777;border-top:1px solid #eeeeee;padding-top:18px;margin:26px 0 0">Cette alerte est générée automatiquement par Crous Alert.<br>Crous Alert n’est pas affilié au CROUS.</p></td></tr></table></td></tr></table></body></html>`;

function escape(value: string): string { return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#039;"); }
function price(min: number | null, max: number | null): string { if (min === null && max === null) return "Prix non précisé"; if (max === null || min === max) return `${((min ?? max ?? 0) / 100).toFixed(2).replace(".", ",")} €`; if (min === null) return `Jusqu'à ${(max / 100).toFixed(2).replace(".", ",")} €`; return `${(min / 100).toFixed(2).replace(".", ",")} à ${(max / 100).toFixed(2).replace(".", ",")} €`; }
function details(item: EmailListing): string { return [item.housing_type === "chambre" ? "Chambre" : "Studio", price(item.price_min_cents, item.price_max_cents), item.surface_m2 === null ? null : `${item.surface_m2} m²`].filter(Boolean).join(" · "); }
function dateLabel(value: string): string { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(date); }
function html(listings: EmailListing[]): string { const cards = listings.map((item) => { const location = `${item.city}${item.postal_code ? ` · ${item.postal_code}` : ""}`; return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #e4e4e4;border-radius:12px;margin:0 0 18px"><tr><td style="padding:20px"><h2 style="font-size:20px;line-height:1.3;margin:0 0 13px;color:#111111">${escape(item.residence)}</h2><p style="margin:7px 0;color:#333333;font-size:14px;line-height:1.5"><strong>Ville :</strong> ${escape(location)}</p><p style="margin:7px 0;color:#333333;font-size:14px;line-height:1.5"><strong>Logement :</strong> ${escape(details(item))}</p><p style="margin:7px 0;color:#777777;font-size:13px;line-height:1.5"><strong>Détecté :</strong> ${escape(dateLabel(item.last_seen_at))}</p><p style="margin:20px 0 0"><a class="cta-button" href="${escape(item.url)}" style="display:block;background:#1769e0;color:#ffffff;text-align:center;font-size:16px;font-weight:bold;padding:15px 12px;border-radius:7px;text-decoration:none">Voir l'annonce sur le site CROUS</a></p></td></tr></table>`; }).join(""); const summary = listings.length === 1 ? "1 logement a été détecté" : `${listings.length} logements ont été détectés`; return template.replace("{{SUMMARY}}", summary).replace("{{CARDS}}", cards); }
function text(listings: EmailListing[]): string { return [`Nouveaux logements CROUS correspondant à votre surveillance`, "", `${listings.length} logement(s) détecté(s) :`, "", ...listings.flatMap((item) => [`- ${item.residence}`, `  ${item.city}${item.postal_code ? ` · ${item.postal_code}` : ""}`, `  ${details(item)}`, `  Détecté : ${dateLabel(item.last_seen_at)}`, `  ${item.url}`, ""]), "Crous Alert n'est pas affilié au CROUS."].join("\n"); }
function base64Url(value: Uint8Array): string { let binary = ""; for (const byte of value) binary += String.fromCharCode(byte); return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function encodedSubject(value: string): string { return `=?UTF-8?B?${base64Url(new TextEncoder().encode(value))}?=`; }

export async function sendGmail(recipient: string, listings: EmailListing[]): Promise<void> {
  const sender = Deno.env.get("EMAIL_SENDER") ?? "crous.alerte.sender@gmail.com";
  const clientId = Deno.env.get("GOOGLE_CLIENT_ID");
  const clientSecret = Deno.env.get("GOOGLE_CLIENT_SECRET");
  const refreshToken = Deno.env.get("GOOGLE_REFRESH_TOKEN");
  if (!clientId || !clientSecret || !refreshToken) throw new Error("Secrets Gmail API manquants.");
  const tokenResponse = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: clientId, client_secret: clientSecret, refresh_token: refreshToken, grant_type: "refresh_token" }) });
  if (!tokenResponse.ok) throw new Error(`Jeton Gmail refusé (${tokenResponse.status}).`);
  const token = await tokenResponse.json() as { access_token?: string };
  if (!token.access_token) throw new Error("Jeton Gmail absent.");
  const boundary = `crous-alert-${crypto.randomUUID()}`;
  const mime = [`From: CROUS Alert <${sender}>`, `To: ${recipient}`, `Subject: ${encodedSubject(`CROUS Alert — ${listings.length} nouveau(x) logement(s)`)}`, "MIME-Version: 1.0", `Content-Type: multipart/alternative; boundary=\"${boundary}\"`, "", `--${boundary}`, "Content-Type: text/plain; charset=UTF-8", "Content-Transfer-Encoding: 8bit", "", text(listings), `--${boundary}`, "Content-Type: text/html; charset=UTF-8", "Content-Transfer-Encoding: 8bit", "", html(listings), `--${boundary}--`, ""].join("\r\n");
  const response = await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send", { method: "POST", headers: { authorization: `Bearer ${token.access_token}`, "content-type": "application/json" }, body: JSON.stringify({ raw: base64Url(new TextEncoder().encode(mime)) }) });
  if (!response.ok) throw new Error(`Envoi Gmail refusé (${response.status}).`);
}
